export const en = {
    lang: 'en',
    signin: 'Sign In',
    logout: 'Logout',
    welcome: 'Welcome to',
    projectName: 'Iber consulting',
    newPost: 'Add Post',
    searchBtn: 'Search',
    keywords: 'Keywords',
    typeSearch: 'Type',
    location: 'Location',
    type: 'Type',
    realEstate: 'Real estate',
    apartment: 'Apartment',
    fond: 'Commercial property',
    exploreTitle: 'Find out your property for sale',
    exploreParag: 'If you can’t immediately see your dream property, do please get in touch with us personally for some recommendations. We welcome a new property into our catalogue.',
    all: 'All',
    sort: 'Sort by',
    date: 'Date',
    rating: 'Rating',
    price: 'Price',

    cities: [
        'Ariana',
        'Beja',
        'Ben Arous',
        'Bizert',
        'Gabes',
        'Nabeul',
        'Jendouba',
        'Kairouan',
        'Kasserine',
        'Kebili',
        'Kef',
        'Mahdia',
        'Manouba',
        'Medenine',
        'Monastir',
        'Gafsa',
        'Sfax',
        'Sidi Bouzid',
        'Siliana',
        'Sousse',
        'Tataouine',
        'Tozeur',
        'Tunis',
        'Zaghouan',
    ]
}

export const fr = {
    lang: 'fr',
    signin: "S'identifier",
    logout: 'Se Déconncter',
    welcome: 'Bienvenue à',
    projectName: 'Iber conseils',
    newPost: 'Ajouter une publication',
    searchBtn: 'Recherche',
    keywords: 'Mots clés',
    typeSearch: 'Type',
    location: 'Emplacement',
    type: 'Type',
    realEstate: 'Immobiliers',
    apartment: 'Appartements',
    fond: 'Fonds de commerce',
    exploreTitle: 'Découvrez votre bien à vendre ou à louer',
    exploreParag: 'Si vous ne pouvez pas voir immédiatement la propriété de vos rêves, veuillez nous contacter personnellement pour obtenir des recommandations. Nous accueillons une nouvelle propriété dans notre catalogue.',
    all: 'Tout',
    sort: 'Trier par',
    date: 'Date',
    rating: 'Evaluation',
    price: 'Prix',

    cities: [
        'Ariana',
        'Beja',
        'Ben Arous',
        'Bizert',
        'Gabes',
        'Nabeul',
        'Jendouba',
        'Kairouan',
        'Kasserine',
        'Kebili',
        'Kef',
        'Mahdia',
        'Manouba',
        'Medenine',
        'Monastir',
        'Gafsa',
        'Sfax',
        'Sidi Bouzid',
        'Siliana',
        'Sousse',
        'Tataouine',
        'Tozeur',
        'Tunis',
        'Zaghouan',
    ]
}

export const ar = {
    lang: 'ar',
    signin: 'تسجيل الدخول',
    logout: 'خروج',
    welcome: 'مرحبا بك في',
    projectName: 'ايبر للاستشارات',
    newPost: 'أضف منشورا',
    searchBtn: 'ابحث',
    keywords: 'الكلمات الدالة',
    typeSearch: 'النوع',
    location: 'المكان',
    type: 'النوع',
    realEstate: 'العقارات',
    apartment: 'الفيلات',
    fond: 'العقارات التجارية',
    exploreTitle: 'اكتشف الممتلكات الخاصة للبيع',
    exploreParag: 'إذا لم تتمكن من رؤية العقار الذي تحلم به على الفور ، فيرجى الاتصال بنا شخصيًا للحصول على بعض التوصيات. نرحب بممتلكات جديدة في الكتالوج الخاص بنا.',
    all: 'الكل',
    sort: 'رتب بـ',
    date: 'التاريخ',
    rating: 'التصنيف',
    price: 'السعر',


    cities: [
        'أريانة',
        'باجة',
        'بن عروس',
        'بنزرت',
        'قابس',
        'نابل',
        'جندوبة',
        'القيروان',
        'القصرين',
        'قبلي',
        'الكاف',
        'المهدية',
        'منوبة',
        'مدنين',
        'المنستير',
        'قفصة',
        'صفاقس',
        'سيدي بوزيد',
        'سليانة',
        'سوسة',
        'طاطوين',
        'توزر',
        'تونس',
        'زغوان',
    ]
}